### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by harrysolovay** [Schniz/cmd-ts#148]
Awesome library. I'm currently using `cmd-ts` within a [Deno](https://github.com/denoland/deno) application. Everything behaves beautifully with one exception: at the end of every run is an error related to (what appears to be) a NodeJS cleanup hook (?).

```
error: Uncaught TypeError: __Process$.exit is not a function
    at N.run (https://cdn.esm.sh/v66/cmd-ts@0.10.0/es2021/cmd-ts.js:2:4443)
    at Module.ve (https://cdn.esm.sh/v66/cmd-ts@0.10.0/es2021/cmd-ts.js:9:66)
    at async file:///Users/harrysolovay/Desktop/capi/cli/bin.ts:8:1
```

Using `dryRun` suppresses this error... but then there's no console output. Any tips on smoothing this out?

**Comment by harrysolovay** [comment]
Just wanted to follow up. I'm a huge fan of this CLI DX and would very much like to continue using it. Thoughts on this issue would be greatly appreciated!

**Comment by Schniz** [comment]
Hey I really want to do that. Having dryRun was to support Deno. Hope I’ll get to this soon

**Comment by harrysolovay** [comment]
@Schniz thank you for your consideration. AWESOME TOOL!

**Comment by harrysolovay** [comment]
Hi @Schniz, any word on whether this feature might make its way into the lib? (no pressure).
